// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: network_connection.proto

#include "network_connection.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

bool ENetworkDisconnectionReason_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
    case 10:
    case 11:
    case 12:
    case 13:
    case 14:
    case 15:
    case 16:
    case 17:
    case 18:
    case 19:
    case 20:
    case 21:
    case 22:
    case 23:
    case 24:
    case 25:
    case 26:
    case 27:
    case 28:
    case 29:
    case 30:
    case 31:
    case 32:
    case 33:
    case 34:
    case 35:
    case 36:
    case 37:
    case 38:
    case 39:
    case 40:
    case 41:
    case 42:
    case 43:
    case 44:
    case 45:
    case 46:
    case 47:
    case 48:
    case 49:
    case 50:
    case 51:
    case 52:
    case 53:
    case 54:
    case 55:
    case 56:
    case 57:
    case 58:
    case 59:
    case 60:
    case 61:
    case 62:
    case 63:
    case 64:
    case 65:
    case 66:
    case 67:
    case 68:
    case 69:
    case 71:
    case 72:
    case 73:
    case 74:
    case 75:
    case 76:
    case 77:
    case 79:
    case 80:
    case 81:
    case 82:
    case 83:
    case 84:
    case 85:
    case 128:
    case 129:
    case 130:
    case 131:
    case 132:
    case 133:
    case 134:
    case 135:
    case 136:
    case 137:
    case 138:
    case 139:
    case 140:
    case 141:
    case 142:
    case 143:
    case 144:
    case 145:
    case 146:
    case 147:
    case 148:
    case 149:
    case 150:
    case 151:
    case 152:
    case 153:
    case 154:
    case 155:
    case 156:
    case 157:
    case 158:
    case 159:
    case 160:
    case 161:
    case 162:
    case 163:
    case 164:
      return true;
    default:
      return false;
  }
}

static ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<std::string> ENetworkDisconnectionReason_strings[121] = {};

static const char ENetworkDisconnectionReason_names[] =
  "NETWORK_DISCONNECT_BADDELTATICK"
  "NETWORK_DISCONNECT_BADRELAYPASSWORD"
  "NETWORK_DISCONNECT_BADSPECTATORPASSWORD"
  "NETWORK_DISCONNECT_BAD_SERVER_PASSWORD"
  "NETWORK_DISCONNECT_BANADDED"
  "NETWORK_DISCONNECT_CLIENT_CONSISTENCY_FAIL"
  "NETWORK_DISCONNECT_CLIENT_DIFFERENT_MAP"
  "NETWORK_DISCONNECT_CLIENT_NO_MAP"
  "NETWORK_DISCONNECT_CLIENT_UNABLE_TO_CRC_MAP"
  "NETWORK_DISCONNECT_CONNECTION_FAILURE"
  "NETWORK_DISCONNECT_CONNECT_REQUEST_TIMEDOUT"
  "NETWORK_DISCONNECT_CREATE_SERVER_FAILED"
  "NETWORK_DISCONNECT_DELTAENTMSG_OVERFLOW"
  "NETWORK_DISCONNECT_DIFFERENTCLASSTABLES"
  "NETWORK_DISCONNECT_DIRECT_CONNECT_RESERVATION"
  "NETWORK_DISCONNECT_DISCONNECTED"
  "NETWORK_DISCONNECT_DISCONNECT_BY_SERVER"
  "NETWORK_DISCONNECT_DISCONNECT_BY_USER"
  "NETWORK_DISCONNECT_EXITING"
  "NETWORK_DISCONNECT_HLTVDIRECT"
  "NETWORK_DISCONNECT_HLTVRESTRICTED"
  "NETWORK_DISCONNECT_HLTVSTOP"
  "NETWORK_DISCONNECT_HLTVUNAVAILABLE"
  "NETWORK_DISCONNECT_HOST_ENDGAME"
  "NETWORK_DISCONNECT_INTERNAL_ERROR"
  "NETWORK_DISCONNECT_INVALID"
  "NETWORK_DISCONNECT_INVALID_MESSAGE_ERROR"
  "NETWORK_DISCONNECT_KICKBANADDED"
  "NETWORK_DISCONNECT_KICKED"
  "NETWORK_DISCONNECT_KICKED_COMPETITIVECOOLDOWN"
  "NETWORK_DISCONNECT_KICKED_CONVICTEDACCOUNT"
  "NETWORK_DISCONNECT_KICKED_HOSTAGEKILLING"
  "NETWORK_DISCONNECT_KICKED_IDLE"
  "NETWORK_DISCONNECT_KICKED_INPUTAUTOMATION"
  "NETWORK_DISCONNECT_KICKED_INSECURECLIENT"
  "NETWORK_DISCONNECT_KICKED_NOSTEAMLOGIN"
  "NETWORK_DISCONNECT_KICKED_NOSTEAMTICKET"
  "NETWORK_DISCONNECT_KICKED_SUICIDE"
  "NETWORK_DISCONNECT_KICKED_TEAMHURTING"
  "NETWORK_DISCONNECT_KICKED_TEAMKILLING"
  "NETWORK_DISCONNECT_KICKED_TK_START"
  "NETWORK_DISCONNECT_KICKED_UNTRUSTEDACCOUNT"
  "NETWORK_DISCONNECT_KICKED_VACNETABNORMALBEHAVIOR"
  "NETWORK_DISCONNECT_KICKED_VOTEDOFF"
  "NETWORK_DISCONNECT_LEAVINGSPLIT"
  "NETWORK_DISCONNECT_LOCALPROBLEM_HOSTEDSERVERPRIMARYRELAY"
  "NETWORK_DISCONNECT_LOCALPROBLEM_MANYRELAYS"
  "NETWORK_DISCONNECT_LOCALPROBLEM_NETWORKCONFIG"
  "NETWORK_DISCONNECT_LOCALPROBLEM_OTHER"
  "NETWORK_DISCONNECT_LOOPDEACTIVATE"
  "NETWORK_DISCONNECT_LOOPSHUTDOWN"
  "NETWORK_DISCONNECT_LOOP_LEVELLOAD_ACTIVATE"
  "NETWORK_DISCONNECT_LOST"
  "NETWORK_DISCONNECT_MESSAGE_PARSE_ERROR"
  "NETWORK_DISCONNECT_NOMORESPLITS"
  "NETWORK_DISCONNECT_NOSPECTATORS"
  "NETWORK_DISCONNECT_NO_PEER_GROUP_HANDLERS"
  "NETWORK_DISCONNECT_OVERFLOW"
  "NETWORK_DISCONNECT_PURESERVER_CLIENTEXTRA"
  "NETWORK_DISCONNECT_PURESERVER_MISMATCH"
  "NETWORK_DISCONNECT_RECONNECTION"
  "NETWORK_DISCONNECT_REJECTED_BY_GAME"
  "NETWORK_DISCONNECT_REJECT_BACKGROUND_MAP"
  "NETWORK_DISCONNECT_REJECT_BADCHALLENGE"
  "NETWORK_DISCONNECT_REJECT_BADPASSWORD"
  "NETWORK_DISCONNECT_REJECT_BANNED"
  "NETWORK_DISCONNECT_REJECT_CONNECT_FROM_LOBBY"
  "NETWORK_DISCONNECT_REJECT_FAILEDCHANNEL"
  "NETWORK_DISCONNECT_REJECT_HIDDEN_GAME"
  "NETWORK_DISCONNECT_REJECT_INVALIDCERTLEN"
  "NETWORK_DISCONNECT_REJECT_INVALIDCONNECTION"
  "NETWORK_DISCONNECT_REJECT_INVALIDKEYLENGTH"
  "NETWORK_DISCONNECT_REJECT_INVALIDRESERVATION"
  "NETWORK_DISCONNECT_REJECT_INVALIDSTEAMCERTLEN"
  "NETWORK_DISCONNECT_REJECT_LANRESTRICT"
  "NETWORK_DISCONNECT_REJECT_NEWPROTOCOL"
  "NETWORK_DISCONNECT_REJECT_NOLOBBY"
  "NETWORK_DISCONNECT_REJECT_OLDPROTOCOL"
  "NETWORK_DISCONNECT_REJECT_RESERVED_FOR_LOBBY"
  "NETWORK_DISCONNECT_REJECT_SERVERAUTHDISABLED"
  "NETWORK_DISCONNECT_REJECT_SERVERCDKEYAUTHINVALID"
  "NETWORK_DISCONNECT_REJECT_SERVERFULL"
  "NETWORK_DISCONNECT_REJECT_SINGLE_PLAYER"
  "NETWORK_DISCONNECT_REJECT_STEAM"
  "NETWORK_DISCONNECT_RELIABLEOVERFLOW"
  "NETWORK_DISCONNECT_REMOTE_BADCRYPT"
  "NETWORK_DISCONNECT_REMOTE_CERTNOTTRUSTED"
  "NETWORK_DISCONNECT_REMOTE_OTHER"
  "NETWORK_DISCONNECT_REMOTE_TIMEOUT"
  "NETWORK_DISCONNECT_REMOTE_TIMEOUT_CONNECTING"
  "NETWORK_DISCONNECT_REPLAY_INCOMPATIBLE"
  "NETWORK_DISCONNECT_REQUEST_HOSTSTATE_HLTVRELAY"
  "NETWORK_DISCONNECT_REQUEST_HOSTSTATE_IDLE"
  "NETWORK_DISCONNECT_SERVERINFO_OVERFLOW"
  "NETWORK_DISCONNECT_SERVER_INCOMPATIBLE"
  "NETWORK_DISCONNECT_SERVER_REQUIRES_STEAM"
  "NETWORK_DISCONNECT_SERVER_SHUTDOWN"
  "NETWORK_DISCONNECT_SHUTDOWN"
  "NETWORK_DISCONNECT_SNAPSHOTERROR"
  "NETWORK_DISCONNECT_SNAPSHOTOVERFLOW"
  "NETWORK_DISCONNECT_SOUNDSMSG_OVERFLOW"
  "NETWORK_DISCONNECT_STEAM_AUTHALREADYUSED"
  "NETWORK_DISCONNECT_STEAM_AUTHCANCELLED"
  "NETWORK_DISCONNECT_STEAM_AUTHINVALID"
  "NETWORK_DISCONNECT_STEAM_BANNED"
  "NETWORK_DISCONNECT_STEAM_DENY_BAD_ANTI_CHEAT"
  "NETWORK_DISCONNECT_STEAM_DENY_MISC"
  "NETWORK_DISCONNECT_STEAM_DROPPED"
  "NETWORK_DISCONNECT_STEAM_INUSE"
  "NETWORK_DISCONNECT_STEAM_LOGGED_IN_ELSEWHERE"
  "NETWORK_DISCONNECT_STEAM_LOGON"
  "NETWORK_DISCONNECT_STEAM_OWNERSHIP"
  "NETWORK_DISCONNECT_STEAM_TICKET"
  "NETWORK_DISCONNECT_STEAM_VACBANSTATE"
  "NETWORK_DISCONNECT_STEAM_VAC_CHECK_TIMEDOUT"
  "NETWORK_DISCONNECT_STRINGTABLEMSG_OVERFLOW"
  "NETWORK_DISCONNECT_TEMPENTMSG_OVERFLOW"
  "NETWORK_DISCONNECT_TICKMSG_OVERFLOW"
  "NETWORK_DISCONNECT_TIMEDOUT"
  "NETWORK_DISCONNECT_UNUSUAL"
  "NETWORK_DISCONNECT_USERCMD";

static const ::PROTOBUF_NAMESPACE_ID::internal::EnumEntry ENetworkDisconnectionReason_entries[] = {
  { {ENetworkDisconnectionReason_names + 0, 31}, 27 },
  { {ENetworkDisconnectionReason_names + 31, 35}, 33 },
  { {ENetworkDisconnectionReason_names + 66, 39}, 34 },
  { {ENetworkDisconnectionReason_names + 105, 38}, 49 },
  { {ENetworkDisconnectionReason_names + 143, 27}, 40 },
  { {ENetworkDisconnectionReason_names + 170, 42}, 62 },
  { {ENetworkDisconnectionReason_names + 212, 39}, 65 },
  { {ENetworkDisconnectionReason_names + 251, 32}, 64 },
  { {ENetworkDisconnectionReason_names + 283, 43}, 63 },
  { {ENetworkDisconnectionReason_names + 326, 37}, 51 },
  { {ENetworkDisconnectionReason_names + 363, 43}, 72 },
  { {ENetworkDisconnectionReason_names + 406, 39}, 58 },
  { {ENetworkDisconnectionReason_names + 445, 39}, 21 },
  { {ENetworkDisconnectionReason_names + 484, 39}, 32 },
  { {ENetworkDisconnectionReason_names + 523, 45}, 50 },
  { {ENetworkDisconnectionReason_names + 568, 31}, 30 },
  { {ENetworkDisconnectionReason_names + 599, 39}, 3 },
  { {ENetworkDisconnectionReason_names + 638, 37}, 2 },
  { {ENetworkDisconnectionReason_names + 675, 26}, 59 },
  { {ENetworkDisconnectionReason_names + 701, 29}, 42 },
  { {ENetworkDisconnectionReason_names + 730, 33}, 35 },
  { {ENetworkDisconnectionReason_names + 763, 27}, 38 },
  { {ENetworkDisconnectionReason_names + 790, 34}, 37 },
  { {ENetworkDisconnectionReason_names + 824, 31}, 56 },
  { {ENetworkDisconnectionReason_names + 855, 33}, 85 },
  { {ENetworkDisconnectionReason_names + 888, 26}, 0 },
  { {ENetworkDisconnectionReason_names + 914, 40}, 48 },
  { {ENetworkDisconnectionReason_names + 954, 31}, 41 },
  { {ENetworkDisconnectionReason_names + 985, 25}, 39 },
  { {ENetworkDisconnectionReason_names + 1010, 45}, 154 },
  { {ENetworkDisconnectionReason_names + 1055, 42}, 153 },
  { {ENetworkDisconnectionReason_names + 1097, 40}, 156 },
  { {ENetworkDisconnectionReason_names + 1137, 30}, 158 },
  { {ENetworkDisconnectionReason_names + 1167, 41}, 162 },
  { {ENetworkDisconnectionReason_names + 1208, 40}, 164 },
  { {ENetworkDisconnectionReason_names + 1248, 38}, 160 },
  { {ENetworkDisconnectionReason_names + 1286, 39}, 161 },
  { {ENetworkDisconnectionReason_names + 1325, 33}, 159 },
  { {ENetworkDisconnectionReason_names + 1358, 37}, 155 },
  { {ENetworkDisconnectionReason_names + 1395, 37}, 150 },
  { {ENetworkDisconnectionReason_names + 1432, 34}, 151 },
  { {ENetworkDisconnectionReason_names + 1466, 42}, 152 },
  { {ENetworkDisconnectionReason_names + 1508, 48}, 163 },
  { {ENetworkDisconnectionReason_names + 1556, 34}, 157 },
  { {ENetworkDisconnectionReason_names + 1590, 31}, 31 },
  { {ENetworkDisconnectionReason_names + 1621, 56}, 75 },
  { {ENetworkDisconnectionReason_names + 1677, 42}, 74 },
  { {ENetworkDisconnectionReason_names + 1719, 45}, 76 },
  { {ENetworkDisconnectionReason_names + 1764, 37}, 77 },
  { {ENetworkDisconnectionReason_names + 1801, 33}, 55 },
  { {ENetworkDisconnectionReason_names + 1834, 31}, 54 },
  { {ENetworkDisconnectionReason_names + 1865, 42}, 57 },
  { {ENetworkDisconnectionReason_names + 1907, 23}, 4 },
  { {ENetworkDisconnectionReason_names + 1930, 38}, 47 },
  { {ENetworkDisconnectionReason_names + 1968, 31}, 28 },
  { {ENetworkDisconnectionReason_names + 1999, 31}, 36 },
  { {ENetworkDisconnectionReason_names + 2030, 41}, 52 },
  { {ENetworkDisconnectionReason_names + 2071, 27}, 5 },
  { {ENetworkDisconnectionReason_names + 2098, 41}, 43 },
  { {ENetworkDisconnectionReason_names + 2139, 38}, 44 },
  { {ENetworkDisconnectionReason_names + 2177, 31}, 53 },
  { {ENetworkDisconnectionReason_names + 2208, 35}, 46 },
  { {ENetworkDisconnectionReason_names + 2243, 40}, 130 },
  { {ENetworkDisconnectionReason_names + 2283, 38}, 128 },
  { {ENetworkDisconnectionReason_names + 2321, 37}, 134 },
  { {ENetworkDisconnectionReason_names + 2358, 32}, 149 },
  { {ENetworkDisconnectionReason_names + 2390, 44}, 138 },
  { {ENetworkDisconnectionReason_names + 2434, 39}, 137 },
  { {ENetworkDisconnectionReason_names + 2473, 37}, 132 },
  { {ENetworkDisconnectionReason_names + 2510, 40}, 144 },
  { {ENetworkDisconnectionReason_names + 2550, 43}, 143 },
  { {ENetworkDisconnectionReason_names + 2593, 42}, 140 },
  { {ENetworkDisconnectionReason_names + 2635, 44}, 136 },
  { {ENetworkDisconnectionReason_names + 2679, 45}, 145 },
  { {ENetworkDisconnectionReason_names + 2724, 37}, 133 },
  { {ENetworkDisconnectionReason_names + 2761, 37}, 142 },
  { {ENetworkDisconnectionReason_names + 2798, 33}, 129 },
  { {ENetworkDisconnectionReason_names + 2831, 37}, 141 },
  { {ENetworkDisconnectionReason_names + 2868, 44}, 139 },
  { {ENetworkDisconnectionReason_names + 2912, 44}, 147 },
  { {ENetworkDisconnectionReason_names + 2956, 48}, 148 },
  { {ENetworkDisconnectionReason_names + 3004, 36}, 135 },
  { {ENetworkDisconnectionReason_names + 3040, 39}, 131 },
  { {ENetworkDisconnectionReason_names + 3079, 31}, 146 },
  { {ENetworkDisconnectionReason_names + 3110, 35}, 26 },
  { {ENetworkDisconnectionReason_names + 3145, 34}, 82 },
  { {ENetworkDisconnectionReason_names + 3179, 40}, 83 },
  { {ENetworkDisconnectionReason_names + 3219, 31}, 81 },
  { {ENetworkDisconnectionReason_names + 3250, 33}, 79 },
  { {ENetworkDisconnectionReason_names + 3283, 44}, 80 },
  { {ENetworkDisconnectionReason_names + 3327, 38}, 71 },
  { {ENetworkDisconnectionReason_names + 3365, 46}, 61 },
  { {ENetworkDisconnectionReason_names + 3411, 41}, 60 },
  { {ENetworkDisconnectionReason_names + 3452, 38}, 18 },
  { {ENetworkDisconnectionReason_names + 3490, 38}, 73 },
  { {ENetworkDisconnectionReason_names + 3528, 40}, 66 },
  { {ENetworkDisconnectionReason_names + 3568, 34}, 69 },
  { {ENetworkDisconnectionReason_names + 3602, 27}, 1 },
  { {ENetworkDisconnectionReason_names + 3629, 32}, 25 },
  { {ENetworkDisconnectionReason_names + 3661, 35}, 24 },
  { {ENetworkDisconnectionReason_names + 3696, 37}, 23 },
  { {ENetworkDisconnectionReason_names + 3733, 40}, 11 },
  { {ENetworkDisconnectionReason_names + 3773, 38}, 10 },
  { {ENetworkDisconnectionReason_names + 3811, 36}, 12 },
  { {ENetworkDisconnectionReason_names + 3847, 31}, 6 },
  { {ENetworkDisconnectionReason_names + 3878, 44}, 68 },
  { {ENetworkDisconnectionReason_names + 3922, 34}, 67 },
  { {ENetworkDisconnectionReason_names + 3956, 32}, 16 },
  { {ENetworkDisconnectionReason_names + 3988, 30}, 7 },
  { {ENetworkDisconnectionReason_names + 4018, 44}, 14 },
  { {ENetworkDisconnectionReason_names + 4062, 30}, 9 },
  { {ENetworkDisconnectionReason_names + 4092, 34}, 17 },
  { {ENetworkDisconnectionReason_names + 4126, 31}, 8 },
  { {ENetworkDisconnectionReason_names + 4157, 36}, 13 },
  { {ENetworkDisconnectionReason_names + 4193, 43}, 15 },
  { {ENetworkDisconnectionReason_names + 4236, 42}, 20 },
  { {ENetworkDisconnectionReason_names + 4278, 38}, 22 },
  { {ENetworkDisconnectionReason_names + 4316, 35}, 19 },
  { {ENetworkDisconnectionReason_names + 4351, 27}, 29 },
  { {ENetworkDisconnectionReason_names + 4378, 26}, 84 },
  { {ENetworkDisconnectionReason_names + 4404, 26}, 45 },
};

static const int ENetworkDisconnectionReason_entries_by_number[] = {
  25, // 0 -> NETWORK_DISCONNECT_INVALID
  97, // 1 -> NETWORK_DISCONNECT_SHUTDOWN
  17, // 2 -> NETWORK_DISCONNECT_DISCONNECT_BY_USER
  16, // 3 -> NETWORK_DISCONNECT_DISCONNECT_BY_SERVER
  52, // 4 -> NETWORK_DISCONNECT_LOST
  57, // 5 -> NETWORK_DISCONNECT_OVERFLOW
  104, // 6 -> NETWORK_DISCONNECT_STEAM_BANNED
  108, // 7 -> NETWORK_DISCONNECT_STEAM_INUSE
  112, // 8 -> NETWORK_DISCONNECT_STEAM_TICKET
  110, // 9 -> NETWORK_DISCONNECT_STEAM_LOGON
  102, // 10 -> NETWORK_DISCONNECT_STEAM_AUTHCANCELLED
  101, // 11 -> NETWORK_DISCONNECT_STEAM_AUTHALREADYUSED
  103, // 12 -> NETWORK_DISCONNECT_STEAM_AUTHINVALID
  113, // 13 -> NETWORK_DISCONNECT_STEAM_VACBANSTATE
  109, // 14 -> NETWORK_DISCONNECT_STEAM_LOGGED_IN_ELSEWHERE
  114, // 15 -> NETWORK_DISCONNECT_STEAM_VAC_CHECK_TIMEDOUT
  107, // 16 -> NETWORK_DISCONNECT_STEAM_DROPPED
  111, // 17 -> NETWORK_DISCONNECT_STEAM_OWNERSHIP
  93, // 18 -> NETWORK_DISCONNECT_SERVERINFO_OVERFLOW
  117, // 19 -> NETWORK_DISCONNECT_TICKMSG_OVERFLOW
  115, // 20 -> NETWORK_DISCONNECT_STRINGTABLEMSG_OVERFLOW
  12, // 21 -> NETWORK_DISCONNECT_DELTAENTMSG_OVERFLOW
  116, // 22 -> NETWORK_DISCONNECT_TEMPENTMSG_OVERFLOW
  100, // 23 -> NETWORK_DISCONNECT_SOUNDSMSG_OVERFLOW
  99, // 24 -> NETWORK_DISCONNECT_SNAPSHOTOVERFLOW
  98, // 25 -> NETWORK_DISCONNECT_SNAPSHOTERROR
  84, // 26 -> NETWORK_DISCONNECT_RELIABLEOVERFLOW
  0, // 27 -> NETWORK_DISCONNECT_BADDELTATICK
  54, // 28 -> NETWORK_DISCONNECT_NOMORESPLITS
  118, // 29 -> NETWORK_DISCONNECT_TIMEDOUT
  15, // 30 -> NETWORK_DISCONNECT_DISCONNECTED
  44, // 31 -> NETWORK_DISCONNECT_LEAVINGSPLIT
  13, // 32 -> NETWORK_DISCONNECT_DIFFERENTCLASSTABLES
  1, // 33 -> NETWORK_DISCONNECT_BADRELAYPASSWORD
  2, // 34 -> NETWORK_DISCONNECT_BADSPECTATORPASSWORD
  20, // 35 -> NETWORK_DISCONNECT_HLTVRESTRICTED
  55, // 36 -> NETWORK_DISCONNECT_NOSPECTATORS
  22, // 37 -> NETWORK_DISCONNECT_HLTVUNAVAILABLE
  21, // 38 -> NETWORK_DISCONNECT_HLTVSTOP
  28, // 39 -> NETWORK_DISCONNECT_KICKED
  4, // 40 -> NETWORK_DISCONNECT_BANADDED
  27, // 41 -> NETWORK_DISCONNECT_KICKBANADDED
  19, // 42 -> NETWORK_DISCONNECT_HLTVDIRECT
  58, // 43 -> NETWORK_DISCONNECT_PURESERVER_CLIENTEXTRA
  59, // 44 -> NETWORK_DISCONNECT_PURESERVER_MISMATCH
  120, // 45 -> NETWORK_DISCONNECT_USERCMD
  61, // 46 -> NETWORK_DISCONNECT_REJECTED_BY_GAME
  53, // 47 -> NETWORK_DISCONNECT_MESSAGE_PARSE_ERROR
  26, // 48 -> NETWORK_DISCONNECT_INVALID_MESSAGE_ERROR
  3, // 49 -> NETWORK_DISCONNECT_BAD_SERVER_PASSWORD
  14, // 50 -> NETWORK_DISCONNECT_DIRECT_CONNECT_RESERVATION
  9, // 51 -> NETWORK_DISCONNECT_CONNECTION_FAILURE
  56, // 52 -> NETWORK_DISCONNECT_NO_PEER_GROUP_HANDLERS
  60, // 53 -> NETWORK_DISCONNECT_RECONNECTION
  50, // 54 -> NETWORK_DISCONNECT_LOOPSHUTDOWN
  49, // 55 -> NETWORK_DISCONNECT_LOOPDEACTIVATE
  23, // 56 -> NETWORK_DISCONNECT_HOST_ENDGAME
  51, // 57 -> NETWORK_DISCONNECT_LOOP_LEVELLOAD_ACTIVATE
  11, // 58 -> NETWORK_DISCONNECT_CREATE_SERVER_FAILED
  18, // 59 -> NETWORK_DISCONNECT_EXITING
  92, // 60 -> NETWORK_DISCONNECT_REQUEST_HOSTSTATE_IDLE
  91, // 61 -> NETWORK_DISCONNECT_REQUEST_HOSTSTATE_HLTVRELAY
  5, // 62 -> NETWORK_DISCONNECT_CLIENT_CONSISTENCY_FAIL
  8, // 63 -> NETWORK_DISCONNECT_CLIENT_UNABLE_TO_CRC_MAP
  7, // 64 -> NETWORK_DISCONNECT_CLIENT_NO_MAP
  6, // 65 -> NETWORK_DISCONNECT_CLIENT_DIFFERENT_MAP
  95, // 66 -> NETWORK_DISCONNECT_SERVER_REQUIRES_STEAM
  106, // 67 -> NETWORK_DISCONNECT_STEAM_DENY_MISC
  105, // 68 -> NETWORK_DISCONNECT_STEAM_DENY_BAD_ANTI_CHEAT
  96, // 69 -> NETWORK_DISCONNECT_SERVER_SHUTDOWN
  90, // 71 -> NETWORK_DISCONNECT_REPLAY_INCOMPATIBLE
  10, // 72 -> NETWORK_DISCONNECT_CONNECT_REQUEST_TIMEDOUT
  94, // 73 -> NETWORK_DISCONNECT_SERVER_INCOMPATIBLE
  46, // 74 -> NETWORK_DISCONNECT_LOCALPROBLEM_MANYRELAYS
  45, // 75 -> NETWORK_DISCONNECT_LOCALPROBLEM_HOSTEDSERVERPRIMARYRELAY
  47, // 76 -> NETWORK_DISCONNECT_LOCALPROBLEM_NETWORKCONFIG
  48, // 77 -> NETWORK_DISCONNECT_LOCALPROBLEM_OTHER
  88, // 79 -> NETWORK_DISCONNECT_REMOTE_TIMEOUT
  89, // 80 -> NETWORK_DISCONNECT_REMOTE_TIMEOUT_CONNECTING
  87, // 81 -> NETWORK_DISCONNECT_REMOTE_OTHER
  85, // 82 -> NETWORK_DISCONNECT_REMOTE_BADCRYPT
  86, // 83 -> NETWORK_DISCONNECT_REMOTE_CERTNOTTRUSTED
  119, // 84 -> NETWORK_DISCONNECT_UNUSUAL
  24, // 85 -> NETWORK_DISCONNECT_INTERNAL_ERROR
  63, // 128 -> NETWORK_DISCONNECT_REJECT_BADCHALLENGE
  76, // 129 -> NETWORK_DISCONNECT_REJECT_NOLOBBY
  62, // 130 -> NETWORK_DISCONNECT_REJECT_BACKGROUND_MAP
  82, // 131 -> NETWORK_DISCONNECT_REJECT_SINGLE_PLAYER
  68, // 132 -> NETWORK_DISCONNECT_REJECT_HIDDEN_GAME
  74, // 133 -> NETWORK_DISCONNECT_REJECT_LANRESTRICT
  64, // 134 -> NETWORK_DISCONNECT_REJECT_BADPASSWORD
  81, // 135 -> NETWORK_DISCONNECT_REJECT_SERVERFULL
  72, // 136 -> NETWORK_DISCONNECT_REJECT_INVALIDRESERVATION
  67, // 137 -> NETWORK_DISCONNECT_REJECT_FAILEDCHANNEL
  66, // 138 -> NETWORK_DISCONNECT_REJECT_CONNECT_FROM_LOBBY
  78, // 139 -> NETWORK_DISCONNECT_REJECT_RESERVED_FOR_LOBBY
  71, // 140 -> NETWORK_DISCONNECT_REJECT_INVALIDKEYLENGTH
  77, // 141 -> NETWORK_DISCONNECT_REJECT_OLDPROTOCOL
  75, // 142 -> NETWORK_DISCONNECT_REJECT_NEWPROTOCOL
  70, // 143 -> NETWORK_DISCONNECT_REJECT_INVALIDCONNECTION
  69, // 144 -> NETWORK_DISCONNECT_REJECT_INVALIDCERTLEN
  73, // 145 -> NETWORK_DISCONNECT_REJECT_INVALIDSTEAMCERTLEN
  83, // 146 -> NETWORK_DISCONNECT_REJECT_STEAM
  79, // 147 -> NETWORK_DISCONNECT_REJECT_SERVERAUTHDISABLED
  80, // 148 -> NETWORK_DISCONNECT_REJECT_SERVERCDKEYAUTHINVALID
  65, // 149 -> NETWORK_DISCONNECT_REJECT_BANNED
  39, // 150 -> NETWORK_DISCONNECT_KICKED_TEAMKILLING
  40, // 151 -> NETWORK_DISCONNECT_KICKED_TK_START
  41, // 152 -> NETWORK_DISCONNECT_KICKED_UNTRUSTEDACCOUNT
  30, // 153 -> NETWORK_DISCONNECT_KICKED_CONVICTEDACCOUNT
  29, // 154 -> NETWORK_DISCONNECT_KICKED_COMPETITIVECOOLDOWN
  38, // 155 -> NETWORK_DISCONNECT_KICKED_TEAMHURTING
  31, // 156 -> NETWORK_DISCONNECT_KICKED_HOSTAGEKILLING
  43, // 157 -> NETWORK_DISCONNECT_KICKED_VOTEDOFF
  32, // 158 -> NETWORK_DISCONNECT_KICKED_IDLE
  37, // 159 -> NETWORK_DISCONNECT_KICKED_SUICIDE
  35, // 160 -> NETWORK_DISCONNECT_KICKED_NOSTEAMLOGIN
  36, // 161 -> NETWORK_DISCONNECT_KICKED_NOSTEAMTICKET
  33, // 162 -> NETWORK_DISCONNECT_KICKED_INPUTAUTOMATION
  42, // 163 -> NETWORK_DISCONNECT_KICKED_VACNETABNORMALBEHAVIOR
  34, // 164 -> NETWORK_DISCONNECT_KICKED_INSECURECLIENT
};

const std::string& ENetworkDisconnectionReason_Name(
    ENetworkDisconnectionReason value) {
  static const bool dummy =
      ::PROTOBUF_NAMESPACE_ID::internal::InitializeEnumStrings(
          ENetworkDisconnectionReason_entries,
          ENetworkDisconnectionReason_entries_by_number,
          121, ENetworkDisconnectionReason_strings);
  (void) dummy;
  int idx = ::PROTOBUF_NAMESPACE_ID::internal::LookUpEnumName(
      ENetworkDisconnectionReason_entries,
      ENetworkDisconnectionReason_entries_by_number,
      121, value);
  return idx == -1 ? ::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString() :
                     ENetworkDisconnectionReason_strings[idx].get();
}
bool ENetworkDisconnectionReason_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, ENetworkDisconnectionReason* value) {
  int int_value;
  bool success = ::PROTOBUF_NAMESPACE_ID::internal::LookUpEnumValue(
      ENetworkDisconnectionReason_entries, 121, name, &int_value);
  if (success) {
    *value = static_cast<ENetworkDisconnectionReason>(int_value);
  }
  return success;
}
const std::string network_connection_token_default("");
// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
